events {}
http {
    server {
        listen 80;

        location /hello {
            proxy_pass http://backend:8080/hello;
        }

        location / {
            proxy_pass http://frontend:80;
        }

        location /api/data {
            proxy_pass http://backend:8080/api/data;
        }
    }
}
